name: Rust checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install nightly toolchain
      run: rustup toolchain install nightly
    - name: Install udeps dependency
      # Debug mode because we're not running it for very long,
      # so optimizations help less than the time it takes to
      # compile with them.
      run: cargo install --debug cargo-udeps
    - name: Formatting
      run: cargo fmt --check --verbose
    - name: Clippy
      run: cargo clippy --all-features -- --deny warnings
    - name: Unused dependencies
      run: cargo +nightly udeps
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Test
      run: cargo test --workspace
    - name: Check Generated Bitboards
      run: cargo run -p bitboard --bin magic-bitboard-generation --features=magic-generation -- --check --file-path board/bitboard/
