name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: cargo install cargo-udeps
    - name: Formatting
      run: cargo fmt --check --verbose
    - name: Clippy
      run: cargo clippy -- --deny warnings
    - name: Unused dependencies
      run: cargo +nightly udeps
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Test
      run: cargo test --workspace
